services:
  _defaults:
    autowire: true
    autoconfigure: true

  DigiConstruct\WebsiteBundle\:
    resource: '../*'
    exclude: '../{DependencyInjection,Entity,Migrations,Tests,Resources}'

  DigiConstruct\WebsiteBundle\Controller\DefaultController:
    tags: ['controller.service_arguments']

  DigiConstruct\WebsiteBundle\Controller\LandingPageController:
    tags: ['controller.service_arguments']
