services:
  _defaults:
    autowire: true
    autoconfigure: true

  DigiConstruct\WebsiteBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Resources}'

  DigiConstruct\WebsiteBundle\Controller\DefaultController:
    tags: ['controller.service_arguments']

  DigiConstruct\WebsiteBundle\Controller\LandingPageController:
    tags: ['controller.service_arguments']

  DigiConstruct\WebsiteBundle\Controller\IndustriesController:
    tags: ['controller.service_arguments']
